CREATE TABLE qbr (
	player varchar(50),
	pos char(2),
	age numeric(5, 3),
	date date,
	league char(3),
	team char(3),
	away varchar(1),
	opponent char(3),
	result varchar(8),
	game_number varchar(2),
	week varchar(2),
	day char(3),
	passes_completed smallint,
	passes_attempted smallint,
	completion_percentage float,
	yards_from_passing smallint,
	passing_touchdowns smallint,
	interceptions smallint,
	passer_rating float,
	sacks_taken float,
	yards_lost_to_sacks float,
	yards_per_pass float,
	adjusted_yards_per_pass float,
PRIMARY KEY(player, date));
